import type { DemoRole } from "../identity/types";
import type { Law544Action, Law544Request, Law544Status } from "../law544/types";
import type { LedgerEvent } from "../ledger/types";

const now = Date.parse("2026-09-13T09:00:00.000Z");

function iso(daysOffset: number): string {
  return new Date(now + daysOffset * 24 * 60 * 60 * 1000).toISOString();
}

function hash(seed: string): string {
  return seed.padEnd(64, seed.at(-1) ?? "0").slice(0, 64);
}

function event(input: {
  requestId: string;
  index: number;
  action: Law544Action;
  fromStatus: Law544Status;
  toStatus: Law544Status;
  signerRole: DemoRole;
  day: number;
  documentHash?: string;
  metadata?: Record<string, string>;
}): LedgerEvent {
  return {
    requestId: input.requestId,
    action: input.action,
    fromStatus: input.fromStatus,
    toStatus: input.toStatus,
    payloadHash: hash(`${input.requestId}${input.index}a`),
    documentHash: input.documentHash,
    signerDidHash: hash(`${input.signerRole}${input.requestId}${input.index}b`),
    signerRole: input.signerRole,
    credentialHash: hash(`${input.signerRole}${input.requestId}${input.index}c`),
    signature: `demo-signature-${input.requestId}-${input.index}`,
    timestamp: iso(input.day),
    metadata: input.metadata,
    index: input.index,
    previousStateHash: input.index === 0 ? hash("0") : hash(`${input.requestId}${input.index - 1}d`),
    stateHash: hash(`${input.requestId}${input.index}d`),
  };
}

export type SeededRequestScenario = {
  request: Law544Request;
  events: LedgerEvent[];
};

export const seededRequestScenarios: SeededRequestScenario[] = [
  {
    request: {
      id: "REQ-2026-0002",
      institution: "Ministry of Finance",
      subject: "Budget execution for a county road program",
      citizenDidHash: hash("citizen-finance"),
      status: "Resolved",
      createdAt: iso(-18),
      deadlineAt: iso(12),
      registryNumber: "MF-544-2026-0002",
      assignedToDidHash: hash("finance-servant").slice(0, 24),
      responseDocumentHash: hash("finance-response"),
    },
    events: [
      event({ requestId: "REQ-2026-0002", index: 0, action: "Request_Created", fromStatus: "Draft", toStatus: "Created", signerRole: "Citizen", day: -18 }),
      event({
        requestId: "REQ-2026-0002",
        index: 1,
        action: "Registry_Assigned",
        fromStatus: "Created",
        toStatus: "Registered",
        signerRole: "RegistryBot",
        day: -17,
        metadata: { registryNumber: "MF-544-2026-0002" },
      }),
      event({
        requestId: "REQ-2026-0002",
        index: 2,
        action: "Task_Routed",
        fromStatus: "Registered",
        toStatus: "Routed",
        signerRole: "Director",
        day: -16,
        metadata: { assignedToDidHash: hash("finance-servant").slice(0, 24) },
      }),
      event({ requestId: "REQ-2026-0002", index: 3, action: "Processing_Started", fromStatus: "Routed", toStatus: "InProgress", signerRole: "PublicServant", day: -15 }),
      event({
        requestId: "REQ-2026-0002",
        index: 4,
        action: "Request_Resolved",
        fromStatus: "InProgress",
        toStatus: "Resolved",
        signerRole: "PublicServant",
        day: -9,
        documentHash: hash("finance-response"),
      }),
    ],
  },
  {
    request: {
      id: "REQ-2026-0003",
      institution: "Ministry of Health",
      subject: "Public procurement data for hospital equipment",
      citizenDidHash: hash("citizen-health"),
      status: "InProgress",
      createdAt: iso(-7),
      deadlineAt: iso(23),
      registryNumber: "MS-544-2026-0104",
      assignedToDidHash: hash("health-servant").slice(0, 24),
    },
    events: [
      event({ requestId: "REQ-2026-0003", index: 0, action: "Request_Created", fromStatus: "Draft", toStatus: "Created", signerRole: "Citizen", day: -7 }),
      event({
        requestId: "REQ-2026-0003",
        index: 1,
        action: "Registry_Assigned",
        fromStatus: "Created",
        toStatus: "Registered",
        signerRole: "RegistryBot",
        day: -7,
        metadata: { registryNumber: "MS-544-2026-0104" },
      }),
      event({
        requestId: "REQ-2026-0003",
        index: 2,
        action: "Task_Routed",
        fromStatus: "Registered",
        toStatus: "Routed",
        signerRole: "Director",
        day: -6,
        metadata: { assignedToDidHash: hash("health-servant").slice(0, 24) },
      }),
      event({ requestId: "REQ-2026-0003", index: 3, action: "Processing_Started", fromStatus: "Routed", toStatus: "InProgress", signerRole: "PublicServant", day: -5 }),
      event({
        requestId: "REQ-2026-0003",
        index: 4,
        action: "Document_Attached",
        fromStatus: "InProgress",
        toStatus: "InProgress",
        signerRole: "PublicServant",
        day: -4,
        documentHash: hash("health-evidence"),
      }),
    ],
  },
  {
    request: {
      id: "REQ-2026-0004",
      institution: "City Hall Bucharest Sector 1",
      subject: "Urban planning authorization register export",
      citizenDidHash: hash("citizen-cityhall"),
      status: "Registered",
      createdAt: iso(-2),
      deadlineAt: iso(28),
      registryNumber: "S1-544-2026-0788",
    },
    events: [
      event({ requestId: "REQ-2026-0004", index: 0, action: "Request_Created", fromStatus: "Draft", toStatus: "Created", signerRole: "Citizen", day: -2 }),
      event({
        requestId: "REQ-2026-0004",
        index: 1,
        action: "Registry_Assigned",
        fromStatus: "Created",
        toStatus: "Registered",
        signerRole: "RegistryBot",
        day: -1,
        metadata: { registryNumber: "S1-544-2026-0788" },
      }),
    ],
  },
  {
    request: {
      id: "REQ-2026-0005",
      institution: "Ministry of Environment",
      subject: "Air quality sensor calibration records",
      citizenDidHash: hash("citizen-environment"),
      status: "ExtensionRequested",
      createdAt: iso(-21),
      deadlineAt: iso(9),
      registryNumber: "MMAP-544-2026-0042",
      assignedToDidHash: hash("environment-servant").slice(0, 24),
    },
    events: [
      event({ requestId: "REQ-2026-0005", index: 0, action: "Request_Created", fromStatus: "Draft", toStatus: "Created", signerRole: "Citizen", day: -21 }),
      event({
        requestId: "REQ-2026-0005",
        index: 1,
        action: "Registry_Assigned",
        fromStatus: "Created",
        toStatus: "Registered",
        signerRole: "RegistryBot",
        day: -20,
        metadata: { registryNumber: "MMAP-544-2026-0042" },
      }),
      event({
        requestId: "REQ-2026-0005",
        index: 2,
        action: "Task_Routed",
        fromStatus: "Registered",
        toStatus: "Routed",
        signerRole: "Director",
        day: -19,
        metadata: { assignedToDidHash: hash("environment-servant").slice(0, 24) },
      }),
      event({ requestId: "REQ-2026-0005", index: 3, action: "Processing_Started", fromStatus: "Routed", toStatus: "InProgress", signerRole: "PublicServant", day: -18 }),
      event({
        requestId: "REQ-2026-0005",
        index: 4,
        action: "Extension_Requested",
        fromStatus: "InProgress",
        toStatus: "ExtensionRequested",
        signerRole: "PublicServant",
        day: -3,
        metadata: { reason: "large-volume-environmental-records" },
      }),
    ],
  },
  {
    request: {
      id: "REQ-2026-0006",
      institution: "National Agency for Cadastre",
      subject: "Dataset publication status for cadastral map updates",
      citizenDidHash: hash("citizen-cadastre"),
      status: "Overdue",
      createdAt: iso(-46),
      deadlineAt: iso(-16),
      registryNumber: "ANCPI-544-2026-0307",
      assignedToDidHash: hash("cadastre-servant").slice(0, 24),
    },
    events: [
      event({ requestId: "REQ-2026-0006", index: 0, action: "Request_Created", fromStatus: "Draft", toStatus: "Created", signerRole: "Citizen", day: -46 }),
      event({
        requestId: "REQ-2026-0006",
        index: 1,
        action: "Registry_Assigned",
        fromStatus: "Created",
        toStatus: "Registered",
        signerRole: "RegistryBot",
        day: -45,
        metadata: { registryNumber: "ANCPI-544-2026-0307" },
      }),
      event({
        requestId: "REQ-2026-0006",
        index: 2,
        action: "Task_Routed",
        fromStatus: "Registered",
        toStatus: "Routed",
        signerRole: "Director",
        day: -43,
        metadata: { assignedToDidHash: hash("cadastre-servant").slice(0, 24) },
      }),
      event({ requestId: "REQ-2026-0006", index: 3, action: "Processing_Started", fromStatus: "Routed", toStatus: "InProgress", signerRole: "PublicServant", day: -41 }),
      event({
        requestId: "REQ-2026-0006",
        index: 4,
        action: "Request_Marked_Overdue",
        fromStatus: "InProgress",
        toStatus: "Overdue",
        signerRole: "RegistryBot",
        day: -15,
        metadata: { missedDeadlineAt: iso(-16) },
      }),
    ],
  },
  {
    request: {
      id: "REQ-2026-0007",
      institution: "National Authority for Consumer Protection",
      subject: "Complaint inspection statistics by county",
      citizenDidHash: hash("citizen-consumer-protection"),
      status: "Rejected",
      createdAt: iso(-13),
      deadlineAt: iso(17),
      registryNumber: "ANPC-544-2026-0155",
      assignedToDidHash: hash("consumer-servant").slice(0, 24),
      responseDocumentHash: hash("consumer-rejection-response"),
    },
    events: [
      event({ requestId: "REQ-2026-0007", index: 0, action: "Request_Created", fromStatus: "Draft", toStatus: "Created", signerRole: "Citizen", day: -13 }),
      event({
        requestId: "REQ-2026-0007",
        index: 1,
        action: "Registry_Assigned",
        fromStatus: "Created",
        toStatus: "Registered",
        signerRole: "RegistryBot",
        day: -12,
        metadata: { registryNumber: "ANPC-544-2026-0155" },
      }),
      event({
        requestId: "REQ-2026-0007",
        index: 2,
        action: "Task_Routed",
        fromStatus: "Registered",
        toStatus: "Routed",
        signerRole: "Director",
        day: -11,
        metadata: { assignedToDidHash: hash("consumer-servant").slice(0, 24) },
      }),
      event({ requestId: "REQ-2026-0007", index: 3, action: "Processing_Started", fromStatus: "Routed", toStatus: "InProgress", signerRole: "PublicServant", day: -10 }),
      event({
        requestId: "REQ-2026-0007",
        index: 4,
        action: "Request_Rejected",
        fromStatus: "InProgress",
        toStatus: "Rejected",
        signerRole: "PublicServant",
        day: -6,
        documentHash: hash("consumer-rejection-response"),
        metadata: { reason: "outside-public-information-scope" },
      }),
    ],
  },
  {
    request: {
      id: "REQ-2026-0008",
      institution: "Ministry of Transport",
      subject: "Rail modernization contract annexes redirected to operator",
      citizenDidHash: hash("citizen-transport"),
      status: "Resolved",
      createdAt: iso(-10),
      deadlineAt: iso(20),
      registryNumber: "MT-544-2026-0091",
      assignedToDidHash: hash("transport-servant").slice(0, 24),
      responseDocumentHash: hash("transport-redirect-response"),
    },
    events: [
      event({ requestId: "REQ-2026-0008", index: 0, action: "Request_Created", fromStatus: "Draft", toStatus: "Created", signerRole: "Citizen", day: -10 }),
      event({
        requestId: "REQ-2026-0008",
        index: 1,
        action: "Registry_Assigned",
        fromStatus: "Created",
        toStatus: "Registered",
        signerRole: "RegistryBot",
        day: -10,
        metadata: { registryNumber: "MT-544-2026-0091" },
      }),
      event({
        requestId: "REQ-2026-0008",
        index: 2,
        action: "Task_Routed",
        fromStatus: "Registered",
        toStatus: "Routed",
        signerRole: "Director",
        day: -9,
        metadata: { assignedToDidHash: hash("transport-servant").slice(0, 24) },
      }),
      event({ requestId: "REQ-2026-0008", index: 3, action: "Processing_Started", fromStatus: "Routed", toStatus: "InProgress", signerRole: "PublicServant", day: -8 }),
      event({
        requestId: "REQ-2026-0008",
        index: 4,
        action: "Request_Resolved",
        fromStatus: "InProgress",
        toStatus: "Resolved",
        signerRole: "PublicServant",
        day: -5,
        documentHash: hash("transport-redirect-response"),
        metadata: { responseType: "redirected", targetInstitution: "National Railway Company" },
      }),
    ],
  },
  {
    request: {
      id: "REQ-2026-0009",
      institution: "Ministry of Education",
      subject: "School renovation grant scoring sheets",
      citizenDidHash: hash("citizen-education"),
      status: "InProgress",
      createdAt: iso(-16),
      deadlineAt: iso(14),
      registryNumber: "ME-544-2026-0440",
      assignedToDidHash: hash("education-servant").slice(0, 24),
    },
    events: [
      event({ requestId: "REQ-2026-0009", index: 0, action: "Request_Created", fromStatus: "Draft", toStatus: "Created", signerRole: "Citizen", day: -16 }),
      event({
        requestId: "REQ-2026-0009",
        index: 1,
        action: "Registry_Assigned",
        fromStatus: "Created",
        toStatus: "Registered",
        signerRole: "RegistryBot",
        day: -15,
        metadata: { registryNumber: "ME-544-2026-0440" },
      }),
      event({
        requestId: "REQ-2026-0009",
        index: 2,
        action: "Task_Routed",
        fromStatus: "Registered",
        toStatus: "Routed",
        signerRole: "Director",
        day: -14,
        metadata: { assignedToDidHash: hash("education-servant").slice(0, 24) },
      }),
      event({ requestId: "REQ-2026-0009", index: 3, action: "Processing_Started", fromStatus: "Routed", toStatus: "InProgress", signerRole: "PublicServant", day: -13 }),
      event({
        requestId: "REQ-2026-0009",
        index: 4,
        action: "Document_Attached",
        fromStatus: "InProgress",
        toStatus: "InProgress",
        signerRole: "PublicServant",
        day: -2,
        documentHash: hash("education-partial-disclosure"),
        metadata: { responseScope: "partial-disclosure", redactionBasis: "third-party-data" },
      }),
    ],
  },
  {
    request: {
      id: "REQ-2026-0010",
      institution: "Ministry of Energy",
      subject: "State aid decision publication timeline",
      citizenDidHash: hash("citizen-energy"),
      status: "ExtensionRequested",
      createdAt: iso(-29),
      deadlineAt: iso(1),
      registryNumber: "MEnergy-544-2026-0028",
      assignedToDidHash: hash("energy-servant").slice(0, 24),
    },
    events: [
      event({ requestId: "REQ-2026-0010", index: 0, action: "Request_Created", fromStatus: "Draft", toStatus: "Created", signerRole: "Citizen", day: -29 }),
      event({
        requestId: "REQ-2026-0010",
        index: 1,
        action: "Registry_Assigned",
        fromStatus: "Created",
        toStatus: "Registered",
        signerRole: "RegistryBot",
        day: -28,
        metadata: { registryNumber: "MEnergy-544-2026-0028" },
      }),
      event({
        requestId: "REQ-2026-0010",
        index: 2,
        action: "Task_Routed",
        fromStatus: "Registered",
        toStatus: "Routed",
        signerRole: "Director",
        day: -27,
        metadata: { assignedToDidHash: hash("energy-servant").slice(0, 24) },
      }),
      event({ requestId: "REQ-2026-0010", index: 3, action: "Processing_Started", fromStatus: "Routed", toStatus: "InProgress", signerRole: "PublicServant", day: -25 }),
      event({
        requestId: "REQ-2026-0010",
        index: 4,
        action: "Extension_Requested",
        fromStatus: "InProgress",
        toStatus: "ExtensionRequested",
        signerRole: "PublicServant",
        day: -1,
        metadata: { reason: "third-party-consultation", extensionDeadlineAt: iso(1) },
      }),
    ],
  },
];
